#!/bin/bash

COLOR_RED="\033[0;31m"
COLOR_YELLOW="\033[0;33m"
COLOR_GREEN="\033[0;32m"
COLOR_OCHRE="\033[38;5;95m"
COLOR_BLUE="\033[0;34m"
COLOR_WHITE="\033[0;37m"

COLOR_RESET="\033[0m"

parse_git_branch() {
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

PS1="\u@\h" # user hostname
PS1+="\[\e[32m\]\w \[\e[91m\]" # working dir
PS1+="\$(parse_git_branch)"
PS1+="\[\e[00m\]$ " # prompt

export PS1
